name: CI DevOps Sprint

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v6

      - name: Preparar Java
        uses: actions/setup-java@v5
        with:
          java-version: '26'
          distribution: 'temurin'

      - name: Ejecutar tests
        run: ./mvnw test
