name: CI DevOps Sprint

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v6

      - name: Preparar Jav
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'
